FROM MAVEN:3.9.8-openjdk:11-jre-slim AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim

WORKDIR /app

COPY - from=build /app/target/my-application.jar ./

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "movies-0.0.6.jar"]
